-- Active: 1663608941518@@127.0.0.1@3306
-- SQLite
CREATE TABLE USERS (Username TEXTE NOT NULL PRIMARY KEY,passwords  TEXT NOT NULL,Email TEXT NOT NULL);

SELECT * FROM USERS;

ALTER TABLE USERS
ADD Email TEXT NOT NULL;

ALTER TABLE "USERS"
MODIFY COLUMN Email TEXT;

INSERT INTO USERS(Username,hash,email) VALUES ('jake','like','buzz@gmail.com');

